name: working with env variables
on: 

  - workflow_dispatch

env:
  APP_ENV: "dev"

jobs:
  env-demo:
    runs-on: ubuntu-latest
    env:
       APP_ENV: "test"
    steps:
      - name: Connecting to env
        env:
          APP_ENV: "prod"
        run: echo "app is connecting to $APP_ENV"
