name: if demo
on:
  push:
   branches:
      - develop

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: if demo eg
        if: github.ref == 'refs/heads/main'
        run: echo "running this step from main branch"

      - name: simple step
        run: echo " runnning this simple step"
