name: hello world
on: 
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: first step
         shell: bash
         run: |
           echo "Welcome to GHA"
           ls -l
           pwd 
           echo "done"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: my test job
        run: echo "test has been completed"

  checking_the-installed_pacakages:
      needs: test
      runs-on: ubuntu-latest
      steps:
       - name: Check installed tools
         run: |
          git --version
          python --version
          node --version
          npm --version
