name: hello world
on: 
  workflow_dispatch:
  push:
    branches:
        -  main
        - 'feature/**'
  pull_request:
       branches:
         - main
       types:
         - opened
         - synchronize
         

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: first step
         if: github.ref == '/refs/heads/feature/pr_demo'
         run: |
           echo "Welcome to GHA"
           ls -l
           pwd 
           echo "done"

